name 'php56-remi'
maintainer 'Toru TAMURA'
maintainer_email 'torut@ttsoft.jp'
license 'MIT License'
description 'Install PHP 5.6 from remi-php56 repository.'
version '1.0'
depends 'yum-remi', '~> 1.0'
